### ISSUE TITLE
Create Level 4

### ISSUE THREAD

**Issue by Chr1zM** [Chr1zM/2D_Platformer#12]
Make a new third level where the finishline is on top of you

**Comment by Chr1zM** [comment]
- [x] is blocked by Walljump feature because of the level design #5 
- [x] is blocked by Trampolin #14 
- [x] is blocked by Fan #15
